services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-80}:3000"
    environment:
      REDIS_HOST: redis
      SERVER_URL: ${SERVER_URL}
    security_opt:
      # make sure to download the chrome.json file beforehand https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json
      - seccomp:./chrome.json
    # alternatively to seccomp you can use --cap-add=SYS_ADMIN
    # cap_add:
    #   - SYS_ADMIN
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
