version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-80}:3000"
    environment:
      REDIS_HOST: redis
    security_opt:
      # make sure to download the chrome.json file beforehand https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json
      - seccomp:$HOME/chrome.json
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    restart: always
