version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-80}:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    restart: always
