version: "3.9"

services:
  thumbengine:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: npm run start

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"