name: Deploy

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker-Compose Remote Deployment
      uses: astappiev/docker-compose-remote-action@master
      with:
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        ssh_host: ${{ secrets.DEPLOY_HOST }}
        ssh_jump_host: ${{ secrets.DEPLOY_JUMP_HOST }}
        ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_host_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
        ssh_jump_public_key: ${{ secrets.DEPLOY_JUMP_PUBLIC_KEY }}
        docker_compose_prefix: thumbengine
        docker_env: HTTP_PORT=7090
